#!/bin/env bash
# set -x
SCRIPTNAME=chroot
show_usage () {
	echo "Usage: $SCRIPTNAME [command]"
	echo "If run without argument, the default shell will be executed"
	echo '-g GNU root $PREFIX/glibc '
	echo '-u Ubuntu root $FILES/ubuntu bash has to be installed and runnable'
	exit 0
}

debian=false
gnu=false
ubuntu=false
while getopts dhgu option
do
	case "$option" in
		d) debian=true;;
		h) show_usage;;
		g) gnu=true;;
		u) ubuntu=true;;
		?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
	esac
done
shift $(($OPTIND-1))

if $debian; then
ROOT=$DATA/debian
name=/d
elif $gnu; then
ROOT=$FILES/usr/glibc
# ROOT0=
name=/g
# ARGS+=" -b $ROOT:/usr"
elif $ubuntu; then
ROOT=$DATA/ubuntu
# ROOT0=
name=/u
else
ROOT=$PREFIX
ROOT0=/..
name=/
fi


if $debian || $ubuntu; then
	:
else
ARGS+=" -b $ROOT:/usr"
for f in bin etc lib share var; do
	ARGS+=" -b $ROOT/$f:/$f"
done
# exit
fi

# Kill processes on exit to avoid hanging on exit
ARGS+=" --kill-on-exit"

ARGS+=" -b /data:/data"
ARGS="$ARGS -b /system:/system"
ARGS="$ARGS -b /vendor:/vendor"
ARGS="$ARGS -b $DATA/tmp:/tmp"
# ARGS="$ARGS -b $ROOT/opt:/opt"

if [ -d /apex ]; then
	ARGS="$ARGS -b /apex:/apex"
fi

# Android 11.
if [ -e "/linkerconfig/ld.config.txt" ]; then
	ARGS="$ARGS -b /linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt"
fi

if [ -f /property_contexts ]; then
	# Used by getprop (see https://github.com/termux/termux-packages/issues/1076)
	# but does not exist on Android 8.
	ARGS="$ARGS -b /property_contexts:/property_contexts"
fi

if [ -d /storage ]; then
	ARGS="$ARGS -b /storage:/storage"
fi

for f in dev proc; do
	ARGS="$ARGS -b /$f:/$f"
done

ARGS+=" -b $HOME:/home"

pwd=$(pwd|sed s,$FILES,,)
# ARGS="$ARGS --cwd=/home"
ARGS="$ARGS --cwd=$pwd"

# Root of the file system:
ARGS="$ARGS -r $ROOT$ROOT0"

# Shell to execute:
PROGRAM=/bin/bash
if [ -x $HOME/.termux/shell ]; then
	PROGRAM=`readlink -f $HOME/.termux/shell`
fi

# export to the new shell
export HOME=/home
export PATH=/bin:$PATH
export PROOT=$ROOT PROOT_NAME=$name
# export PS1="$name \w "
export PS1="\[\e[0;34m\]$name \[\e[0;32m\]\w\[\e[0m\] "
# export PS1="\[\e[0;32m\]\w \[\e[0;34m\]$name \[\e[0m\]" 

# Execute shell if no command has been supplied
if [ -z "$1" ];then
	# ARGS="$ARGS $PROGRAM -l"
	ARGS="$ARGS $PROGRAM "
	echo $ARGS | sed 's,-,\n-,g'
	exec $PREFIX/bin/proot $ARGS
else
	ARGS="$ARGS --cwd=."
	exec $PREFIX/bin/proot $ARGS sh -c "$*"
fi
