#!/bin/env bash
# set -x
SCRIPTNAME=chroot
show_usage () {
	echo "Usage: $SCRIPTNAME [command]"
	echo "If run without argument, the default shell will be executed"
	echo '-g GNU root $PREFIX/glibc '
	echo '-u Ubuntu root $DATA/ubuntu bash has to be installed and runnable'
	exit 0
}

bionic=false
debian=false
gnu=false
ubuntu=false
shebang=false
test $# -eq 0 && bionic=true
while getopts dhgu option
do
	case "$option" in
		d) debian=true;;
		h) show_usage;;
		g) gnu=true;;
		u) ubuntu=true;;
		?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
	esac
done
shift $(($OPTIND-1))

if $debian; then
ROOT=$DATA/debian
name=d
elif $ubuntu; then
ROOT=$DATA/ubuntu
name=u
elif $gnu; then
ROOT=$FILES/usr/glibc
name=/g
# ARGS+=" -b $ROOT:/usr"
else
ROOT=$FILES/usr
name=/
fi

ARGS+=" -r $ROOT"

if $bionic || $gnu; then
ARGS+=" -b $ROOT:/usr"

# for f in bin etc lib share var; do
# 	ARGS+=" -b $ROOT/$f:/$f"
# done

fi


ARGS+=" -b /data:/data"
ARGS+=" -b /system:/system"
ARGS="$ARGS -b /vendor:/vendor"
ARGS="$ARGS -b $DATA/tmp:/tmp"
# ARGS="$ARGS -b $ROOT/opt:/opt"

if [ -d /apex ]; then
	ARGS="$ARGS -b /apex:/apex"
fi

# Android 11.
if [ -e "/linkerconfig/ld.config.txt" ]; then
	ARGS="$ARGS -b /linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt"
fi

if [ -f /property_contexts ]; then
	ARGS="$ARGS -b /property_contexts:/property_contexts"
fi

ARGS+=" -b /storage:/storage"
ARGS+=" -b /sdcard:/sdcard"

for f in dev proc; do
	ARGS="$ARGS -b /$f:/$f"
done

ARGS+=" -b $HOME:/home"

pwd=$(pwd|sed s,$FILES,,)
# ARGS="$ARGS --cwd=/home"
ARGS+=" --cwd=$pwd"

ARGS+=" --kill-on-exit"

# Shell to execute:
PROGRAM=/bin/bash
# PROGRAM=/bin/ksh
# PROGRAM=/bin/sh
if [ -x $HOME/.termux/shell ]; then
	PROGRAM=`readlink -f $HOME/.termux/shell`
fi

# export to the new shell
export HOME=/home
export PATH=/bin:$PATH
export PROOT=$ROOT PROOT_NAME=$name
# export PS1="$name \w "
export PS1="\[\e[0;34m\]$name \[\e[0;32m\]\w\[\e[0m\] "
# export PS1="\[\e[0;32m\]\w \[\e[0;34m\]$name \[\e[0m\]" 
unset LD_PRELOAD

# Execute shell if no command has been supplied
if [ -z "$1" ];then
	# ARGS+="$PROGRAM -l"
	ARGS+=" $PROGRAM  -i  "
	# ARGS+=" $PROGRAM --restricted --verbose --norc --noprofile --noediting -i"
	# ARGS+=" $PROGRAM "
	# echo proot $ARGS 
	# echo $ARGS | sed 's,-,\n-,g'
	exec $PREFIX/bin/proot $ARGS
else
	ARGS="$ARGS --cwd=."
	exec $PREFIX/bin/proot $ARGS sh -c "$*"
fi
