#!/bin/env bash
# set -x
# exec &> >(tee ~/sync.log)
# exec &> >(les)
# exec > >(les)

# g=~/gps
t=~/tmp/wttr
f=~/wttr
j=~/wttr.json
r=~/rain
i=~/nrk

# getprop|ack airp|ack 1 && exit
# age=$(stat -c%Y $f)
# limit=$((EPOCHSECONDS - 6 * 3600))
# if $(($age < $limit)); then
# test "$1" = -g &&	rm $g
# test "$1" = -r &&	rm $f

# if ! test -f $g; then
# 	termux-api-start
# 	termux-location -r last|jq -r '"\(.latitude),\(.longitude)"' > $g
# fi
# gps=$(cat $g)

gps() {
gps=$(termux-location -r last)
lat=$(echo $gps|jq .latitude)
lon=$(echo $gps|jq .longitude)
gps=$lat,$lon
# echo $gps
# exit
}

# if ! test -f $f; then
if test "$1" = -r; then
	gps
	# echo updating weather contact wttr  
	curl  v2.wttr.in/$gps?T > $t
	test -s $t && cp $t $f -v 
	curl  wttr.in/$gps?format=j1  > $j
	finger -- $gps@graph.no > $i
fi

n=$(cat $i)
w=$(cat $f|sed 's/\xf//g'|sed 's/\xef\xb8\x8f//g')
c=$(tput cols)
h=$((1+$(date +"%k")))
age=$(((EPOCHSECONDS - $(stat -c%Y $i) + 3600/2) / 3600))

log(){
# echo c=$c
# echo h=$h
echo age=$age
# echo gps=$gps
# ls -l $i $f 
stat -c%z $i $f 
}
# log
# exit

legend() {
echo "$w"|grep Location
echo "$w"|grep Now
echo "$w"|grep Dusk
echo "$n"|tail -3|head -2
}

n(){
# echo "$n"
# echo "$n"|colrm $c
# echo "$n"|colrm 4 $h|colrm $c
echo "$n"|tail -19|head -15 |colrm 4 $((4+$age*3))
# if wrap
# |colrm $c
}

 w(){
# echo "$w"
ww=$(echo "$w"|head -4|tail -1)
# ww+=$(echo)
ww+="\n"
# ww+="123"
# echo -e "$ww"
# printf "$ww"
# exit
# |colrm 1 $h
# echo "$w"|colrm 5 $((5+$h))|colrm $c
# echo "$w"|head -20|colrm 5 $((5+$h))|colrm $c
ww+=$(echo "$w"|tail -26|head -13)
# printf "$ww"
# exit
echo -e "$ww"|colrm 1 $h
# |colrm $c
}

echo
n
echo
w

# jq '.weather[].hourly[] | "\(.time),\(.chanceofrain)"' $j

echo
legend
